### ISSUE TITLE
Toast

### ISSUE THREAD

**Issue by Jademhm** [WTTJ/welcome-ui#1466]
[Link to Figma](https://www.figma.com/file/TC5aahnPVDU1hhBcff037e/Feedback?node-id=0%3A1)

**Comment by Leiksa** [comment]
@Jademhm pour check le design -> https://v5-callout--welcome-ui.netlify.app/components/toast

**Comment by Jademhm** [comment]
Looks good!

Just a tiny feedback on the close button. It is indeed 24px and the icon inside of it is also the right size (16px), yet it feels like the close icon is bigger than on Figma 🤔 Any idea?

Other than this close icon size issue it's all good to me 👌🏼

**Comment by Leiksa** [comment]
Yeah, i saw this issue when i was styling the close button and it seems that the problem comes from the fact that on figma the icon has spacing and does not fill 100% of the square. (cf screen)
![Screenshot 2022-08-25 at 14 16 40](https://user-images.githubusercontent.com/36013102/186662026-cd3b637d-5d80-440a-8fdc-97a73448d3ce.png)
![Screenshot 2022-08-25 at 14 16 01](https://user-images.githubusercontent.com/36013102/186662044-671af056-f986-4467-b31c-e0e588f9a035.png)
