### ISSUE TITLE
Accordion/styles.js calls filterComponent incorrectly

### ISSUE THREAD

**Issue by agriffis** [WTTJ/welcome-ui#705]
## 😭 Bug report 
filterComponent calls omit from xstyled which expects an array, but this passes a string instead:

https://github.com/WTTJ/welcome-ui/blob/09fb5874969078e10e31e787e14471d41cd466df/packages/Accordion/styles.js#L11

https://github.com/WTTJ/welcome-ui/blob/09fb5874969078e10e31e787e14471d41cd466df/packages/Accordion/styles.js#L44

I've filed a couple issues similar to this one, just things I've noticed while auditing the code. I don't want to annoy anybody though. Please let me know if you'd like me to keep filing these.

**Comment by P1X3L** [comment]
hi @agriffis, thank you for this issue, we are currently working on a better solution using styled-components `shouldForwardProp` (cf https://styled-components.com/docs/api#shouldforwardprop / https://github.com/WTTJ/welcome-ui/pull/685)instead of our custom `filterComponent`.
You don't annoy anyone with your contributions and can keep on filing these 👍 , I'm going to open a pr to correct these two though.

**Comment by theo-mesnil** [comment]
Thanks to @P1X3L  ! It's now on https://github.com/WTTJ/welcome-ui/releases/tag/v2.0.0-alpha.17
